name: Integration Tests

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  store-integration-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        db: [postgres, mysql, mariadb] # safe DBs to start with
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - name: Integration test setup
        uses: ./.github/actions/integration-test-setup

      - name: Run DB tests
        run: |
          KC_TEST_DATABASE=${{ matrix.db }} \
          KC_TEST_DATABASE_REUSE=true \
          TESTCONTAINERS_REUSE_ENABLE=true \
          ./mvnw package -f tests/pom.xml -Dtest=DatabaseTestSuite -Dkeycloak.distribution.start.timeout=360
